# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
show_excerpts: true
title: PixelRabbit's Ponderings
author: Zach Bauer
email: zach@pixelrabbit.me
defaultIMG: "https://www.lorecentral.org/2017/11/advantages-disadvantages-javascript.html"
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog
url: "http://pixelrabbit.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PixelRabbitCode
github_username:  zbauer91
linkedin_username: zachbauer
phone: 6145193442
# Start of information fror the about me section. Just to give a timeline on this.
# I first abstracted it out of HTML into an JS object. Now it's finding it's home in my YAML config file.
# Times sure do change :P
home_page:
  hero_image: "/jekyll-blog/assets/images/hero.jpg"
  header: "Zach Bauer"
  subheader: "<Awesome Web Developer/>"
about_me:
  photo: "/jekyll-blog/assets/images/photo.jpg"
  photo_alt: "A photo of Zach's cute face!"
  tagline: "An expert at turning caffeine and lack of sleep into code"
  brand: "I'm always on the lookout for new, creative ways to solve problems. Whether that be in the work I do professionally, or at home, I'm a practiced MacGyver of programming."


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  load_paths:
    - _sass
    - node_modules
include: [/vendor/]
exclude: [vendor/bundle]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
